################################################################################
###                                 SymSeq                                   ###
################################################################################
symseq:
  ################################################################################
  # Generator
  ################################################################################
  generator:
    type: "ArtificialGrammar"
    mode: "random"  # "preset" | "random" | "custom"
    seed: 42
    constraints:
      label: "Constrained Random Grammar"
      alphabet_size: 4
      ambiguities: 2
      ambiguity_depth: 2
      n_start_states: 1
      transition_density: 0.25
      assume_equiprobable: true
      min_string_length: 1
      eos: "#"


################################################################################
###                                 SeqBench                                 ###
################################################################################
seqbench:
    
    seed: 42
    mode: "file"  # "offline", "online" or "file"
    prob_generator_type: "restricted"

    data_generation:
        train_size: 100
        test_size: 100
        seq_len_min: 1
        seq_len_max: 20
        combine_sequences: True  # concatenate sequences
        combined_seq_length: 20  # padding
        regenerate: False
        output_dir: 'data/SeqBench'

    input_mapping:  # or dataset_mapping / input_mapping / embedding / dataset?
      base: "one_hot"
    
    gap_profile:
        start: 0
        duration:
            dist: "uniform"
            params: {low: 5, high: 5}
        add_nongramm_gap: False  # anomaly stuff, not noise but non-grammatical symbol / deviant
        dt: 0.1