dataset:
  seed: 42
  alphabet:
    size: 4
    eos: "#"
  trial_length:
    min: 1
    max: 20
  splits:
    train: 100
    test: 100

symseq:
  generator:
    type: "ArtificialGrammar"
    mode: "random"
    params:
      label: "Constrained Random Grammar"
      ambiguities: 2
      ambiguity_depth: 2
      n_start_states: 1
      transition_density: 0.25
      assume_equiprobable: true
  tasks:
    - {name: "next_token", type: "NStepPrediction", params: {n: 1}}

seqbench:
  mode: "file"
  prob_generator_type: "restricted"
  time_grid:
    dt: 0.01
    validation: error
  storage:
    path: "data/SeqBench"
    force_rebuild: false
  composition:
    combine_sequences: true
    sample_length: 20
    gap_profile:
      start: 0
      duration: {dist: "uniform", params: {low: 5, high: 5}}  # seconds
  input_mapping:
    base: "dvsgesture"
    base_params:
      download: true
      base_dataset_path: "datasets/DVSGesture"
    transforms:
      - name: tonic.transforms.ToFrame
        sensor_size: [128, 128, 2]
        time_window: 10000.0
        time_behavior: {kind: create, out_dt: 0.01}
      - name: torch.tensor
        dtype: torch.float32
        time_behavior: preserve
      - name: CenterCrop
        sensor_size: [128, 128, 2]
        output_size: [10, 10]
      - name: Flatten
        start_dim: 1
  task:
    source: "symseq"
    name: "next_token"
