run:
  seed: 42

symbol_space:
  alphabet:
    size: 10
  eos: "#"

symseq:
  generator:
    type: ArtificialGrammar
    mode: random
    params:
      label: Constrained Random Grammar
      ambiguities: 0
      ambiguity_depth: 0
      n_start_states: 1
      transition_density: 0.25
      assume_equiprobable: true
  trial_constraints:
    length:
      min: 1
      max: 20
  tasks:
    - id: next_token
      type: NStepPrediction
      params:
        n: 1

seqbench:
  mode: file
  prob_generator_type: restricted
  splits:
    train: 100
    test: 100
  time_grid:
    dt: 0.001
  storage:
    path: data/SeqBench
    force_rebuild: false
  composition:
    combine_sequences: true
    sample_length: 20
  input_mapping:
    base: gsc
    base_params:
      bin_size: 10
      base_dataset_path: datasets/GSC
      split: training
      return_raw: true
    transforms:
      - type: MFCC
        params:
          sample_rate: 16000
          n_mfcc: 13
          n_mels: 40
          n_fft: 512
          win_length: 400
          hop_length: 160
      - type: AdaptivePercentileNorm
        params:
          floor_percentile: 10.0
          ceil_percentile: 90.0
      - type: PowerLaw
        params:
          gamma: 5.0
      - type: ExpandDim
        params:
          axis: 1
          target_size: 700
      - type: RateCoding
        params:
          max_rate: 100.0
          normalize: true
      - type: PoissonEncoding
        params:
          temporal: true
          spike_dt: 0.001
      - type: BinAlongAxis
        params:
          bin_size: 5
          bin_axis: -1
          reduction: binary
  task:
    source: symseq
    ref_id: next_token
