dataset:
  seed: 42
  alphabet:
    size: 10
    eos: "#"
  trial_length:
    min: 1
    max: 20
  splits:
    train: 100
    test: 100

symseq:
  generator:
    type: "ArtificialGrammar"
    mode: "random"
    params:
      label: "Constrained Random Grammar"
      ambiguities: 0
      ambiguity_depth: 0
      n_start_states: 1
      transition_density: 0.25
      assume_equiprobable: true
  tasks:
    - {name: "next_token", type: "NStepPrediction", params: {n: 1}}

seqbench:
  mode: "file"
  prob_generator_type: "restricted"
  storage:
    path: "data/SeqBench"
    force_rebuild: false
  composition:
    combine_sequences: true
    sample_length: 20
  input_mapping:
    base: "one_hot"
    base_params: {}
    transforms:
      - name: ExpandDim
        axis: 1
        target_size: 700
      - name: TemporalConvolution
        kernel_spec:
          shape: "alpha"
          params:
            tau: 20.0
            width: 100.0
        dt: 1.0
        duration: 100.0
        amp: 10.0
      - name: RateCoding
        max_rate: 100.0
        normalize: true
      - name: PoissonEncoding
        temporal: true
        frame_dt: 0.001
        spike_dt: 0.001
  task:
    source: "symseq"
    name: "next_token"
