run:
  seed: 43

symbol_space:
  alphabet:
    size: 4
  eos: "#"

symseq:
  generator:
    type: ArtificialGrammar
    mode: random
    params:
      label: Constrained Random Grammar
      ambiguities: 2
      ambiguity_depth: 2
      n_start_states: 1
      transition_density: 0.25
      assume_equiprobable: true
  trial_constraints:
    length:
      min: 1
      max: 5
  tasks:
    - id: next_token
      type: NStepPrediction
      params:
        n: 1

seqbench:
  mode: file
  prob_generator_type: restricted
  splits:
    train: 100
    test: 100
  time_grid:
    dt: 0.01
  storage:
    path: data/SeqBench
    force_rebuild: false
  composition:
    combine_sequences: true
    sample_length: 5
    gap_profile:
      start: 0
      duration:
        dist: uniform
        params:
          low: 0.5
          high: 0.5
  input_mapping:
    base: shd
    base_params:
      inp_size: 700
      max_time: 1.4
      nb_steps: 140
      spatial_bin_size: 5
      base_dataset_path: datasets/SHD
    transforms: []
  task:
    source: symseq
    ref_id: next_token
