################################################################################
###                                 SymSeq                                   ###
################################################################################
symseq:
  ################################################################################
  # Generator
  ################################################################################
  generator:
    type: "ArtificialGrammar"
    mode: "random"  # "preset" | "random" | "custom"
    seed: 42
    constraints:
      label: "Constrained Random Grammar"
      alphabet_size: 4
      ambiguities: 2
      ambiguity_depth: 2
      n_start_states: 1
      transition_density: 0.25
      assume_equiprobable: true
      min_string_length: 1
      eos: "#"


################################################################################
###                                 SeqBench                                 ###
################################################################################
seqbench:
    
    seed: 43
    mode: "file"  # "offline", "online" or "file"
    prob_generator_type: "restricted"

    data_generation:
        train_size: 100
        test_size: 100
        seq_len_min: 1
        seq_len_max: 20
        combine_sequences: True  # concatenate sequences
        combined_seq_length: 20  # padding
        regenerate: False
        output_dir: 'data/SeqBench'

    # TODO @Younes - finalize this
    input_mapping:
      base: "shd"
      inp_size: 700
      max_time: 1.4
      nb_steps: 140
      spatial_bin_size: 5  # YB: not used fix
      base_dataset_path: 'datasets/SHD'
    
    gap_profile:
      start: 0
      duration: {dist: "uniform", params: {low: 5, high: 5}}
      dt: 0.1  